stages:
  - build

job:
  stage: build
  
  script:
    - echo "Trying build solution..."
    - "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe"  /m /p:Configuration=Release /p:Platform=Win32 /t:rebuild "Awesome.sln"
    - C:\NUnit\nunit-console\nunit3-console.exe " ConsoleApplication1.sln"

  tags:
    - awesome
  
  except: